/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vt5vUuZAFK0
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

import React from "react";
import Link from "next/link";
import { Button } from "../ui/button";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from "../ui/dropdown-menu";
import { Card, CardHeader, CardTitle, CardContent } from "../ui/card";

export default function dashboard_20240714() {
  return (
    <div className="grid min-h-screen w-full grid-cols-[240px_1fr] gap-4 bg-gradient-to-b from-primary to-background p-4 md:grid-cols-[240px_1fr] lg:grid-cols-[240px_1fr] lg:p-8 transition-colors duration-500">
      <header className="col-span-2 flex items-center justify-end bg-background rounded-lg p-2">
        <nav className="flex items-center gap-4">
          <Link
            href="#"
            className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 text-sm font-medium text-primary-foreground shadow transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
            prefetch={false}
          >
            Login
          </Link>
          <Button variant="outline" size="sm">
            Add Viewers
          </Button>
          <Button variant="outline" size="sm">
            Generate Report
          </Button>
          <Button variant="outline" size="sm">
            Upload Financials
          </Button>
          <Button variant="outline" size="sm">
            Email PDF
          </Button>
        </nav>
      </header>
      <div className="flex flex-col gap-4 bg-background rounded-lg p-4">
        <nav className="grid gap-2">
          <Link
            href="#"
            className="flex items-center gap-2 px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}
          >
            <LayoutGridIcon className="w-5 h-5" />
            OKR Board
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}
          >
            <Columns2Icon className="w-5 h-5" />
            Portal
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}
          >
            <CodeIcon className="w-5 h-5" />
            Development
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}
          >
            <PaletteIcon className="w-5 h-5" />
            Backdrop Build
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}
          >
            <BriefcaseIcon className="w-5 h-5" />
            Hubspot
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}
          >
            <BriefcaseIcon className="w-5 h-5" />
            Carta
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}
          >
            <BriefcaseIcon className="w-5 h-5" />
            Gusto
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}
          >
            <BriefcaseIcon className="w-5 h-5" />
            Bench
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}
          >
            <SlackIcon className="w-5 h-5" />
            Slack
          </Link>
          <Link
            href="#"
            className="flex items-center gap-2 px-3 py-2 rounded-md hover:bg-accent hover:text-accent-foreground"
            prefetch={false}
          >
            <LightbulbIcon className="w-5 h-5" />
            Idea board
          </Link>
        </nav>
        <div className="flex flex-col gap-4">
          <div className="flex items-center gap-2">
            <CalendarIcon className="w-5 h-5" />
            <span className="font-medium">Date Range</span>
          </div>
          <div className="flex items-center gap-2">
            <div />
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button
                  variant="outline"
                  size="sm"
                  className="flex items-center gap-2"
                >
                  <span>1d</span>
                  <ChevronDownIcon className="w-4 h-4" />
                </Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent align="end">
                <DropdownMenuItem>1 day</DropdownMenuItem>
                <DropdownMenuItem>1 week</DropdownMenuItem>
                <DropdownMenuItem>1 month</DropdownMenuItem>
                <DropdownMenuItem>1 quarter</DropdownMenuItem>
                <DropdownMenuItem>1 year</DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          </div>
        </div>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="rounded-lg border-none bg-gradient-to-b from-background to-primary">
          <CardHeader className="p-4 border-b border-secondary">
            <CardTitle className="text-white">Sales</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4 p-4">
            <div className="flex items-center justify-between p-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="text-5xl font-bold text-secondary">$500K</div>
                <div className="flex items-center justify-end text-sm text-muted-foreground">
                  +8% YoY
                </div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="flex items-start justify-between">
                <div className="grid gap-1">
                  <div className="text-sm font-medium text-muted-foreground">
                    Planned vs Actual Revenue
                  </div>
                  <div className="text-3xl font-bold text-warning">92%</div>
                </div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="flex items-start justify-between">
                <div className="grid gap-1">
                  <div className="text-sm font-medium text-muted-foreground">
                    New Revenue
                  </div>
                  <div className="text-3xl font-bold text-primary">$125K</div>
                  <div className="text-sm text-muted-foreground">+12%</div>
                </div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="flex items-start justify-between">
                <div className="grid gap-1">
                  <div className="text-sm font-medium text-muted-foreground">
                    Existing Revenue
                  </div>
                  <div className="text-3xl font-bold text-muted-foreground">
                    $375K
                  </div>
                  <div className="text-sm text-muted-foreground">+5%</div>
                </div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="flex items-start justify-between">
                <div className="grid gap-1">
                  <div className="text-sm font-medium text-muted-foreground">
                    Pipeline
                  </div>
                  <div className="text-3xl font-bold text-success">$1.2M</div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="rounded-lg border-none bg-gradient-to-b from-background to-primary">
          <CardHeader className="p-4 border-b border-secondary">
            <CardTitle className="text-white">OPEX</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4 p-4">
            <div className="flex items-center justify-between p-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="text-5xl font-bold text-secondary">$300K</div>
                <div className="flex items-center justify-end text-sm text-muted-foreground">
                  -5% YoY
                </div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="flex items-start justify-between">
                <div className="grid gap-1">
                  <div className="text-sm font-medium text-muted-foreground">
                    Monthly Runway
                  </div>
                  <div className="text-3xl font-bold text-info">6</div>
                </div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="flex items-start justify-between">
                <div className="grid gap-1">
                  <div className="text-sm font-medium text-muted-foreground">
                    Profit per Product
                  </div>
                  <div className="text-3xl font-bold text-warning">$25K</div>
                </div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="flex items-start justify-between">
                <div className="grid gap-1">
                  <div className="text-sm font-medium text-muted-foreground">
                    COGS
                  </div>
                  <div className="text-3xl font-bold text-info">$200K</div>
                </div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="flex items-start justify-between">
                <div className="grid gap-1">
                  <div className="text-sm font-medium text-muted-foreground">
                    Burn Rate
                  </div>
                  <div className="text-3xl font-bold text-warning">$150K</div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="rounded-lg border-none bg-gradient-to-b from-background to-primary">
          <CardHeader className="p-4 border-b border-secondary">
            <CardTitle className="text-white">Culture</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4 p-4">
            <div className="flex items-center justify-between p-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="text-5xl font-bold text-secondary">8.5/10</div>
                <div className="flex items-center justify-end text-sm text-muted-foreground">
                  +0.5 YoY
                </div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="flex items-center justify-between">
                <div className="grid gap-1">
                  <div className="text-sm font-medium text-muted-foreground">
                    Business Improvement Ideas
                  </div>
                  <div className="text-3xl font-bold text-primary">12</div>
                </div>
              </div>
            </div>
            <div className="grid gap-4">
              <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
                <div className="flex items-start justify-between">
                  <div className="grid gap-1">
                    <div className="text-sm font-medium text-muted-foreground">
                      Employee Headcount
                    </div>
                    <div className="text-3xl font-bold text-secondary">125</div>
                    <div className="text-sm text-muted-foreground">
                      +10% YoY
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="grid gap-4">
              <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
                <div className="flex items-start justify-between">
                  <div className="grid gap-1">
                    <div className="text-sm font-medium text-muted-foreground">
                      Contractor Headcount
                    </div>
                    <div className="text-3xl font-bold text-secondary">25</div>
                    <div className="text-sm text-muted-foreground">+5% YoY</div>
                  </div>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card className="rounded-lg border-none bg-gradient-to-b from-background to-primary">
          <CardHeader className="p-4 border-b border-secondary">
            <CardTitle className="text-white">Product</CardTitle>
          </CardHeader>
          <CardContent className="grid gap-4 p-4">
            <div className="flex items-center justify-between p-4">
              <div className="grid grid-cols-2 gap-4">
                <div className="text-5xl font-bold text-secondary">92%</div>
                <div className="flex items-center justify-end text-sm text-muted-foreground">
                  +3% YoY
                </div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="grid gap-1">
                <div className="text-sm font-medium text-muted-foreground">
                  New Customers
                </div>
                <div className="text-3xl font-bold text-primary">1,250</div>
                <div className="text-sm text-muted-foreground">+15% YoY</div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="grid gap-1">
                <div className="text-sm font-medium text-muted-foreground">
                  Product Roadmap Completion
                </div>
                <div className="text-3xl font-bold text-secondary">85%</div>
                <div className="text-sm text-muted-foreground">+10% YoY</div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="grid gap-1">
                <div className="text-sm font-medium text-muted-foreground">
                  Monthly Active Users
                </div>
                <div className="text-3xl font-bold text-info">125K</div>
                <div className="text-sm text-muted-foreground">+20% YoY</div>
              </div>
            </div>
            <div className="grid gap-4 p-4 background border bg-background border-background rounded-lg">
              <div className="grid gap-1">
                <div className="text-sm font-medium text-muted-foreground">
                  Signup-to-First-API-Call Duration
                </div>
                <div className="text-3xl font-bold text-warning">12s</div>
                <div className="text-sm" />
              </div>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function BriefcaseIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M16 20V4a2 2 0 0 0-2-2h-4a2 2 0 0 0-2 2v16" />
      <rect width="20" height="14" x="2" y="6" rx="2" />
    </svg>
  );
}

function CalendarIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>
  );
}

function ChevronDownIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 9 6 6 6-6" />
    </svg>
  );
}

function CodeIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>
  );
}

function Columns2Icon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="18" height="18" x="3" y="3" rx="2" />
      <path d="M12 3v18" />
    </svg>
  );
}

function LayoutGridIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="7" height="7" x="3" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="3" rx="1" />
      <rect width="7" height="7" x="14" y="14" rx="1" />
      <rect width="7" height="7" x="3" y="14" rx="1" />
    </svg>
  );
}

function LightbulbIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 14c.2-1 .7-1.7 1.5-2.5 1-.9 1.5-2.2 1.5-3.5A6 6 0 0 0 6 8c0 1 .2 2.2 1.5 3.5.7.7 1.3 1.5 1.5 2.5" />
      <path d="M9 18h6" />
      <path d="M10 22h4" />
    </svg>
  );
}

function PaletteIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="13.5" cy="6.5" r=".5" fill="currentColor" />
      <circle cx="17.5" cy="10.5" r=".5" fill="currentColor" />
      <circle cx="8.5" cy="7.5" r=".5" fill="currentColor" />
      <circle cx="6.5" cy="12.5" r=".5" fill="currentColor" />
      <path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10c.926 0 1.648-.746 1.648-1.688 0-.437-.18-.835-.437-1.125-.29-.289-.438-.652-.438-1.125a1.64 1.64 0 0 1 1.668-1.668h1.996c3.051 0 5.555-2.503 5.555-5.554C21.965 6.012 17.461 2 12 2z" />
    </svg>
  );
}

function SlackIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <rect width="3" height="8" x="13" y="2" rx="1.5" />
      <path d="M19 8.5V10h1.5A1.5 1.5 0 1 0 19 8.5" />
      <rect width="3" height="8" x="8" y="14" rx="1.5" />
      <path d="M5 15.5V14H3.5A1.5 1.5 0 1 0 5 15.5" />
      <rect width="8" height="3" x="14" y="13" rx="1.5" />
      <path d="M15.5 19H14v1.5a1.5 1.5 0 1 0 1.5-1.5" />
      <rect width="8" height="3" x="2" y="8" rx="1.5" />
      <path d="M8.5 5H10V3.5A1.5 1.5 0 1 0 8.5 5" />
    </svg>
  );
}

function XIcon(props: React.SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  );
}
